### ISSUE TITLE
DA: Náhled

### ISSUE THREAD

**Issue by Euvit** [speedy236/smart-phrase#4]
http://www.smart-phrase.com/hvordan-ser-ipad-konversation-ud - také chybí podnadpis a logo, ale tak to chybí u všech náhledů v dánštině, tj. u Windows 8 a u Androidu

**Comment by speedy236** [comment]
Podnadpis chybí všude; o tom jsme se bavili. Loga jsem přidal.

**Comment by Euvit** [comment]
tak trošku to stím asi souvisí - nyní nefungují drobečky například na http://smart-language.com/nahled-klasicka-anglictina-ios, kde je:
Úvod - OK
**Náhled - NOK**
Klasická angličtina - OK
iOS - OK
