### ISSUE TITLE
DA: Náhled - texty

### ISSUE THREAD

**Issue by Euvit** [speedy236/smart-phrase#5]
http://www.smart-phrase.com/hvordan-ser-konversation-ud-windows8 - podle logiky věci by v popisu, kde jsem, mělo být „Eksempler til Windows 8“ a ne „Windows 8: Eksempler“, když už je to tak jednou přeloženo pro iOS na webu ismartphrase: tj.: Indledning / Eksempler / Eksempler til Windows 8. A nebo to rovnou zkrátit jen takto: Indledning / Eksempler / Windows 8. Stejná chyba je i u Androidu

**Comment by speedy236** [comment]
Zkráceno stejně jako u ostatních verzí už dříve. Tohle mi asi uteklo.
